### ISSUE TITLE
AboveGround Generator

### ISSUE THREAD

**Issue by pkuehne** [pkuehne/fortress#43]
- [ ] Create a big meadow covering the whole map
- [ ] Add trees
- [ ] Vary the tiles and colours for the grass
- [ ] Add plant bushes
- [ ] Add ponds
- [ ] Add brooks
